# wrangler.toml

# General Worker settings
main = ".open-next/worker.js"
compatibility_date = "2025-06-13
workers_dev = false

# Compatibility Flags
# wrangler.toml supports string arrays
compatibility_flags = [
	"nodejs_compat",
	"nodejs_compat_populate_process_env",
]

# Assets configuration (if you have a static assets directory)
[assets] # Note: The closing bracket was missing in your original input, I've corrected it.
directory = ".open-next/assets"
binding = "ASSETS" # This is the variable name that will be available in your Worker to access assets

# Observability (Logging and Monitoring)
[observability] # Note: The closing bracket was missing in your original input, I've corrected it.
enabled = true

[placement]
mode = "smart"

[env.production]
routes = ["demian.inflalite.com/*"]

[env.development]
name = "portfolio-development"
routes = ["dev.demian.inflalite.com/*"]
