# wrangler.toml

# General Worker settings
compatibility_date = "2025-06-13"
workers_dev = false
main = ".open-next/worker.js"
name = "portfolio"

# Compatibility Flags
# wrangler.toml supports string arrays
compatibility_flags = [
	"nodejs_compat",
	"nodejs_compat_populate_process_env",
]

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "portfolio-cache"
preview_bucket_name = "local-prod-cache-bucket"

[durable_objects.bindings]
name = "NEXT_CACHE_DO_QUEUE"
class_name = "DOQueueHandler"

[[migrations]]
tag = "v1"
new_classes = [ "DOQueueHandler" ]

# Assets configuration (if you have a static assets directory)
[assets] # Note: The closing bracket was missing in your original input, I've corrected it.
directory = ".open-next/assets"
binding = "ASSETS" # This is the variable name that will be available in your Worker to access assets

# Observability (Logging and Monitoring)
[observability]
enabled = true

[placement]
mode = "smart"

[env.development]
name = "portfolio-development"

[[env.development.r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "dev-portfolio-cache"
preview_bucket_name = "local-dev-cache-bucket"

[[env.development.durable_objects.bindings]]
name = "NEXT_CACHE_DO_QUEUE"
class_name = "DOQueueHandler"

[[env.development.migrations]]
tag = "v1"
new_sqlite_classes = ["DOQueueHandler"]