name: DEVELOPMENT build

on:
  workflow_dispatch:

concurrency:
  group: dev-$
  cancel-in-progress: true

jobs:
  web_build:
    uses: demian-ilnytskyi/workflows/.github/workflows/next_js_build.yml@main
    secrets: inherit
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    with:
      FLAVOUR: "development"
      cloudflare_secrets: |
        NEXT_PUBLIC_TELEGRAM_BOT_TOKEN: ${{ env.TELEGRAM_BOT_TOKEN }}
        NEXT_PUBLIC_TELEGRAM_SEND_CHAT_ID: ${{ env.TELEGRAM_CHAT_ID }}
