name: DEVELOPMENT build

on:
  workflow_dispatch:

concurrency:
  group: dev-$
  cancel-in-progress: true

jobs:
  web_build:
    uses: demian-ilnytskyi/workflows/.github/workflows/next_js_build.yml@main
    secrets: inherit
    with:
      FLAVOUR: "development"
      secrets_map: |
        TELEGRAM_BOT_TOKEN: TELEGRAM_BOT_TOKEN
        TELEGRAM_SEND_CHAT_ID: TELEGRAM_CHAT_ID
